window-height = 25
window-width = 100
window-theme = ghostty
cursor-style-blink = true
cursor-style = block
linux-cgroup = always
shell-integration = zsh
clipboard-paste-protection = false
font-family = JetbrainsMono Nerd Font
font-size = 12
scrollbar = never
theme = Adwaita Dark
term = xterm-256color
